# Copyright (c) 2026 ADBC Drivers Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Render blog post dates and authors from ABlog front matter."""

from datetime import datetime

from ablog.post import PostNode
from dateutil.parser import parse as parse_date
from docutils import nodes
from sphinx.application import Sphinx
from sphinx.util.typing import ExtensionMetadata
from sphinx.writers.html import HTMLTranslator


class BlogPostMeta(nodes.General, nodes.Element):
    """A blog post's generated date and author byline."""


class BlogPostDate(nodes.Inline, nodes.TextElement):
    """A machine-readable publication date."""


def _visit_blog_post_meta_html(translator: HTMLTranslator, node: BlogPostMeta) -> None:
    translator.body.append(translator.starttag(node, "p", suffix=""))


def _depart_blog_post_meta_html(translator: HTMLTranslator, node: BlogPostMeta) -> None:
    translator.body.append("</p>\n")


def _visit_blog_post_date_html(translator: HTMLTranslator, node: BlogPostDate) -> None:
    translator.body.append(
        translator.starttag(
            node,
            "time",
            suffix="",
            datetime=node["datetime"],
        )
    )


def _depart_blog_post_date_html(translator: HTMLTranslator, node: BlogPostDate) -> None:
    translator.body.append("</time>")


def _visit_passthrough(translator: object, node: nodes.Node) -> None:
    """Render a custom node's children without additional markup."""


def _depart_passthrough(translator: object, node: nodes.Node) -> None:
    """Finish rendering a custom node without additional markup."""


def _published_date(value: str, date_format: str) -> datetime:
    """Parse a publication date using the same rules as ABlog."""
    try:
        return datetime.strptime(value, date_format)
    except ValueError:
        return parse_date(value)


def _author_names(app: Sphinx, post: PostNode) -> list[str]:
    """Return configured display names for a post's authors."""
    authors = post.get("author") or app.config.blog_default_author or []
    if isinstance(authors, str):
        authors = [authors]

    return [
        app.config.blog_authors.get(author, (author, None))[0] for author in authors
    ]


def _add_blog_post_meta(app: Sphinx, doctree: nodes.document) -> None:
    """Insert a generated byline after a front-matter blog post's title."""
    post = next(doctree.findall(PostNode), None)
    if post is None or not post.get("date"):
        return

    section = post.parent
    if not isinstance(section, nodes.section):
        return

    published = _published_date(post["date"], app.config.post_date_format)
    author_names = _author_names(app, post)

    byline = BlogPostMeta(classes=["blog-post-meta"])
    byline += BlogPostDate(
        "",
        published.strftime(app.config.post_date_format),
        datetime=published.date().isoformat(),
    )
    if author_names:
        byline += nodes.Text(" ")
        byline += nodes.inline(
            "",
            ", ".join(author_names),
            classes=["blog-post-author"],
        )

    title_index = next(
        (
            index
            for index, child in enumerate(section.children)
            if isinstance(child, nodes.title)
        ),
        None,
    )
    if title_index is not None:
        section.insert(title_index + 1, byline)


def setup(app: Sphinx) -> ExtensionMetadata:
    """Register the blog post metadata transform and custom nodes."""
    passthrough = (_visit_passthrough, _depart_passthrough)
    app.add_node(
        BlogPostMeta,
        html=(_visit_blog_post_meta_html, _depart_blog_post_meta_html),
        latex=passthrough,
        man=passthrough,
        texinfo=passthrough,
        text=passthrough,
    )
    app.add_node(
        BlogPostDate,
        html=(_visit_blog_post_date_html, _depart_blog_post_date_html),
        latex=passthrough,
        man=passthrough,
        texinfo=passthrough,
        text=passthrough,
    )
    # Run before ABlog's default-priority doctree-read listener snapshots the
    # post for excerpts and full-text feeds.
    app.connect("doctree-read", _add_blog_post_meta, priority=400)
    return {
        "parallel_read_safe": True,
        "parallel_write_safe": True,
    }
